### ISSUE TITLE
您好，有个问题请教下。

### ISSUE THREAD

**Issue by lovebaicai** [shisiying/tc_zufang#2]

**Comment by lovebaicai** [comment]
您好：
     我这边现在写爬虫，我已经有个一个种子库，就不用在使用抓取的url去push到redis了，怎么才能让爬虫去直接读取我种子库的内容呢？

**Comment by shisiying** [comment]
你是使用scrapy-redis，还是使用scrapy，如果是scrapy，直接使用start_urls，，如果是scrapy-redis的话，直接配置从从你的redis读取，具体可见我的项目tc_zufang-slave,这个就是读取tc_zufang产生的待爬取种子

**Comment by lovebaicai** [comment]
谢谢您！我是使用scrapy-redis来读取，我看了您的slave的代码，是在tczufang_detail_spider.py这个里面实现的吗？

**Comment by shisiying** [comment]
是的，就下面这句，配置种子的key，爬虫运行的时候就会从这个key上面获取待爬取url
class TczufangSpider(RedisSpider):
    name='tczufang'
    redis_key = 'tczufang_tc:requests

**Comment by lovebaicai** [comment]
tczufang_detail_spider.py中，redis_key = 'tczufang_tc:requests' 这个redis的key，是表示只获取详情页的url来爬取吗？

**Comment by shisiying** [comment]
对的，keys是你自己自定义的，主要种子库是这个就好了

**Comment by lovebaicai** [comment]
那我就用master，直接把获取的url插入种子库，r.rpush('start_urls', http://item.yunhou.com/10403000059.html’)，然后使用redis_key = 'market:start_urls'，来获取这个redis的url，这个是OK的吧？

**Comment by shisiying** [comment]
没毛病，原理就是这样，主要连上同一个redis服务

**Comment by lovebaicai** [comment]
我修改了一版，但是跑的时候会卡住，您有时间的话，帮忙看看，谢谢！
https://github.com/lovebaicai/learnpython/tree/master/testdemo
